# Please change file name into config.py
keywords=["Russia","Ukraine"]
tweepy_api_key=''
tweepy_key_secret=''
tweepy_access_token=''
tweepy_access_token_secret=''
s3_tweets_uncleaned=""
s3_tweets_cleaned=""
s3_ngram = ""
credential_aws_key=""
credential_aws_secret=""
since='2022-12-03'
until='2022-12-05'
timediff=5
number=10 #Number of tweets to be collected (Max)
loglevel="ERROR"
#ngram_start=3 # Archieve
#ngram_ends=3 # Archieve
summarizer_max_ngram_size=3
summarizer_deduplication_threshold=0.9
summarizer_numOfKeywords=3
bool_date_absolute=True
bool_date_relative=False
bool_get_keyword=True
bool_store_rawdata_cwd=True
bool_store_cleaneddata_cwd=True
bool_store_rawdata_s3=False
bool_store_cleaneddata_s3=False
delimeter='|'